// Mock data for development and testing
import type { PublicMenuItem, PublicTopping } from "@/lib/types/public-order"

export const mockMenuItems: PublicMenuItem[] = [
  {
    id: "menu-1",
    name: "Grilled Chicken Burger",
    description: "Juicy grilled chicken with fresh vegetables",
    price: 12.99,
    category: "Burgers",
    image: "/grilled-chicken-burger.jpg",
  },
  {
    id: "menu-2",
    name: "Classic Beef Burger",
    description: "Premium beef patty with cheese and bacon",
    price: 14.99,
    category: "Burgers",
    image: "/beef-burger.png",
  },
  {
    id: "menu-3",
    name: "Vegetarian Burger",
    description: "Plant-based patty with avocado",
    price: 11.99,
    category: "Burgers",
    image: "/vegetarian-burger.png",
  },
  {
    id: "menu-4",
    name: "Caesar Salad",
    description: "Fresh romaine with parmesan and croutons",
    price: 9.99,
    category: "Salads",
    image: "/caesar-salad.png",
  },
  {
    id: "menu-5",
    name: "Greek Salad",
    description: "Tomatoes, cucumbers, feta cheese, olives",
    price: 10.99,
    category: "Salads",
    image: "/greek-salad.png",
  },
  {
    id: "menu-6",
    name: "Margherita Pizza",
    description: "Fresh mozzarella, basil, tomato sauce",
    price: 13.99,
    category: "Pizza",
    image: "/margherita-pizza.png",
  },
  {
    id: "menu-7",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni with mozzarella",
    price: 14.99,
    category: "Pizza",
    image: "/pepperoni-pizza.png",
  },
  {
    id: "menu-8",
    name: "Vegetarian Pizza",
    description: "Bell peppers, mushrooms, onions, olives",
    price: 13.99,
    category: "Pizza",
    image: "/vegetarian-pizza.jpg",
  },
  {
    id: "menu-9",
    name: "Iced Tea",
    description: "Refreshing cold iced tea",
    price: 2.99,
    category: "Beverages",
    image: "/iced-tea.png",
  },
  {
    id: "menu-10",
    name: "Soft Drink",
    description: "Coca-Cola, Sprite, or Fanta",
    price: 2.49,
    category: "Beverages",
    image: "/refreshing-soft-drink.png",
  },
  {
    id: "menu-11",
    name: "Chocolate Cake",
    description: "Rich chocolate cake with frosting",
    price: 5.99,
    category: "Desserts",
    image: "/decadent-chocolate-cake.png",
  },
  {
    id: "menu-12",
    name: "Cheesecake",
    description: "Creamy New York style cheesecake",
    price: 6.99,
    category: "Desserts",
    image: "/classic-cheesecake.png",
  },
]

export const mockToppings: PublicTopping[] = [
  { id: "topping-1", name: "Extra Cheese", price: 1.5 },
  { id: "topping-2", name: "Bacon", price: 2.0 },
  { id: "topping-3", name: "Mushrooms", price: 1.0 },
  { id: "topping-4", name: "Onions", price: 0.5 },
  { id: "topping-5", name: "Jalapeños", price: 0.75 },
  { id: "topping-6", name: "Avocado", price: 2.5 },
]
